### ISSUE TITLE
"idf.py storage-flash" failed with "Invalid head of packet (0x6F): Possible serial noise or corruption"

### ISSUE THREAD

**Issue by goodluckrhj** [espressif/esp-wasmachine#2]
- Environment:
Ubuntu 22.04
ESP-IDF 4.4.3
esp-wasmachine master

- Description:
After build process, idf.py storage-flash failed. 

- Detailed:
`
~/Project/esp/esp-wasmachine$ idf.py storage-flash
Executing action: storage-flash
Running ninja in directory /home//Project/esp/esp-wasmachine/build
Executing "ninja storage-flash"...
[1/2] cd /home//Project/esp/esp-wasmachine/build/esp-idf/main && /home/...s 0x7f0000 -p 256 -b 4096 /home/Project/esp/esp-wasmachine/build/storage.bin
/wasm/hello_world.wasm
[1/2] cd /home/Project/esp/esp-wasmachine/main && /usr/bin/cmake -D IDF_PATH...ld" -P /home/Project/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
Note: /home/.espressif/python_env/idf4.4_py3.10_env/bin/python /home/Project/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32s3 will search for a serial port. To specify a port, set the ESPPORT environment variable.
Note: /home/.espressif/python_env/idf4.4_py3.10_env/bin/python /home/Project/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32s3 will attempt to set baud rate automatically. To specify a baud rate, set the ESPBAUD environment variable.
esptool.py esp32s3 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 80m --flash_size 16MB 0x810000 storage.bin
esptool.py v3.3.2
Found 1 serial ports
Serial port /dev/ttyACM0
Connecting...
Chip is ESP32-S3
Features: WiFi, BLE
Crystal is 40MHz
MAC: 7c:df:a1:e8:23:58
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00810000 to 0x00ffffff...
Compressed 8323072 bytes to 8656...
Writing at 0x00810000... (100 %)

A fatal error occurred: Invalid head of packet (0x6F): Possible serial noise or corruption.
CMake Error at /home/Project/esp/esp-idf/components/esptool_py/run_serial_tool.cmake:56 (message):
  /home/.espressif/python_env/idf4.4_py3.10_env/bin/python
  /home/Project/esp/esp-idf/components/esptool_py/esptool/esptool.py
  --chip esp32s3 failed

FAILED: esp-idf/main/CMakeFiles/storage-flash /home/Project/esp/esp-wasmachine/build/esp-idf/main/CMakeFiles/storage-flash 
cd /home/Project/esp/esp-wasmachine/main && /usr/bin/cmake -D IDF_PATH="/home/Project/esp/esp-idf" -D SERIAL_TOOL="/home/.espressif/python_env/idf4.4_py3.10_env/bin/python /home/Project/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32s3" -D SERIAL_TOOL_ARGS="--before=default_reset --after=hard_reset write_flash @storage-flash_args" -D WORKING_DIRECTORY="/home/Project/esp/esp-wasmachine/build" -P /home/Project/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
ninja: build stopped: subcommand
`

**Comment by goodluckrhj** [comment]
supplementary information:

1. I have happened to succeeded to flash file system to esp-box **for just only once**. 
2. It always failed to "idf.py storage-flash" or write file system "storage.bin" by "esptool.py"
3. It normally succeeded to "idf.py flash"  to write bootloader or other binary

**Comment by goodluckrhj** [comment]
> 

https://github.com/espressif/arduino-esp32/issues/7467#issue-1446612604
reproduce of this error.

**Comment by donghengqaz** [comment]
This is related to issue:https://github.com/espressif/esptool/issues/795, I have fix this by reducing file-system image size.

**Comment by henrygab** [comment]
Note: reduction to less than 16MB flash use is a workaround only, and for devices using 32MB flash, this issue will cause artificial limiting of the device to <16MB.

**Comment by donghengqaz** [comment]
> Note: reduction to less than 16MB flash use is **_not_** a fix, only a workaround. For devices using 32MB flash, this workaround artificially limits the device to using <16MB of the flash.

Yes, this is a workaround, and I am wait for esptool maintainer to fix this, firstly I try to let users of this SDK feel smooth to flash image.

**Comment by X-Ryl669** [comment]
I think it's fixed (since [this commit](https://github.com/espressif/esptool/commit/b746aa721bee4d29e58914cfeed49590a995fa31), so you can probably restore the expected partition here).
