### ISSUE TITLE
The support verison of wasmachine

### ISSUE THREAD

**Issue by TAOFOR4** [espressif/esp-wasmachine#4]
Hi,

Esp-wasmachine is really a good job! Thx for working. I wonder if you will update it to support devices like ESP32 C6. Because from the README file, I didn't see any support for ESP32 C6.

Thank you!

**Comment by donghengqaz** [comment]
Hi @TAOFOR4,

Yes, we plan to add other platform, like ESP32-C3, ESP32-C6, ESP32-P4 and so on. If you would like to use ESP32-C6, we can prioritize to support it.

**Comment by TAOFOR4** [comment]
> Hi @TAOFOR4,
> 
> Yes, we plan to add other platform, like ESP32-C3, ESP32-C6, ESP32-P4 and so on. If you would like to use ESP32-C6, we can prioritize to support it.

Hi, thx for the reply.  Nice to hear that. :) I have an ESP32-C6 right now. If Esp-wasmachine can support it soon, it will be good because I am planning to do some performance testing on it. (energy consumption, memory size, execution time, etc..
It may also get some interesting analysis for Esp-wasmachine.

**Comment by gordonlukch** [comment]
> Hi @TAOFOR4,
> 
> Yes, we plan to add other platform, like ESP32-C3, ESP32-C6, ESP32-P4 and so on. If you would like to use ESP32-C6, we can prioritize to support it.

Dear  all,

I also interesting on Esp-wasmachine and have ESP32-C6 (DevKitM-1) as well. if esp-wasmachine could support ESP32-C6 soon, it would be nice. Thx  ;-)

**Comment by donghengqaz** [comment]
@TAOFOR4 @gordonlukch Of course, I will add C6 support and sync it to github as soon as possible.

**Comment by donghengqaz** [comment]
Hi, @TAOFOR4 @gordonlukch 

The ESP32-C6 support has been added to the mainline, you can directly use it, the default configuration is based on C6 4MB flash.

**Comment by gordonlukch** [comment]
Great and thanks for hard work👍

**Comment by TAOFOR4** [comment]
Thank you! :)

**Comment by ammaree** [comment]
Any chance to upgrade for IDF v5 support?

On 18 Apr 2024, at 13:51, Tao Xiong ***@***.***> wrote:

﻿

Thank you! :)

**Comment by wujiangang** [comment]
> Any chance to upgrade for IDF v5 support?

You can use any tagged version or release branch from v5.0 onwards.

Close the issue, and feel free to raise new ones if you encounter any further issues.
